### ISSUE TITLE
рефакторинг

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-signup-form#1]
https://github.com/DenisPitsul/react-signup-form/blob/8773f7cd87af27604422ca8137c9de1c53ca8715/src/components/SignUpForm/index.jsx#L57-L70
- я б перенесла обчислення `isPasswordConfirmationValid` в `isSubmitBtnDisabled`, оскільки він нам потрібен тільки там, а так на кожен рендер розраховується. Сильно тут, звісно, не виграєш, але в інших подібних ситуація це може бути більш виграшно за ресурсами.

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-signup-form/commit/af71a94573b9d1a688023a48953303014e151887
